services:

  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run uvicorn --factory app.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy

  user_tg_bot:
    container_name: user_tg_bot
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run python -m app.bots.user_tg_bot.main"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy

  driver_tg_bot:
    container_name: driver_tg_bot
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run python -m app.bots.driver_tg_bot.main"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy

  user_tg_bot_consumer:
    container_name: user_tg_bot_consumer
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run faststream run --factory app.bots.user_tg_bot.consumer.main:get_app --reload"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy

  driver_tg_bot_consumer:
    container_name: driver_tg_bot_consumer
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run faststream run --factory app.bots.driver_tg_bot.consumer.main:get_app --reload"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy

  dispatcher:
    container_name: dispatcher
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    networks:
      - backend_network
    env_file:
      - ./.env
    command: "poetry run faststream run --factory app.dispatcher.main:get_app --reload"
    restart: always
    depends_on:
      backend_postgres:
        condition: service_healthy  
      backend_redis:
        condition: service_healthy  

  backend_postgres:
    image: postgis/postgis:16-3.4
    container_name: backend_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "database"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend_redis: 
    image: redis:latest
    container_name: backend_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redis_data:

networks:
  backend_network:
    name: backend_network
    driver: bridge



